apiVersion: v1
kind: Service
metadata:
  name: {{ include "kerberos.primary.fullname" . }}
  annotations:
    {{- if .Values.primary.service.annotations }}          
    {{- toYaml .Values.primary.service.annotations | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/component: {{ include "kerberos.primary.fullname" . }}
    {{- if .Values.primary.service.labels }}          
    {{- toYaml .Values.primary.service.labels | nindent 4 }}
    {{- end }}
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  externalTrafficPolicy: Cluster
  ports:
    - name: admin-port
      port: {{ .Values.ports.admin }}
      protocol: TCP
      targetPort: admin-port
    - name: kpasswd-port
      port: {{ .Values.ports.kpasswd }}
      protocol: TCP
      targetPort: kpasswd-port
    - name: kdc-port
      port: {{ .Values.ports.kdc }}
      protocol: TCP
      targetPort: kdc-port
  selector:
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/component: {{ include "kerberos.primary.fullname" . }}
