apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kerberos.primary.fullname" . }}
  labels:
    app.kubernetes.io/release: {{ .Release.Name }}
    app.kubernetes.io/component: {{ include "kerberos.primary.fullname" . }}
